/*
 * ESP32 OTA Security Keys
 * Auto-generated by generate_keys.py
 * 
 * ⚠️  SECURITY WARNING: These keys are embedded in firmware!
 * ⚠️  In production, use secure key storage (efuse, secure boot, etc.)
 */

#ifndef OTA_KEYS_H
#define OTA_KEYS_H

#include <stdint.h>

// RSA-2048 Public Key for signature verification
extern const char* SERVER_PUBLIC_KEY;

// AES-256 Key for firmware decryption (32 bytes)
extern const uint8_t AES_FIRMWARE_KEY[32];

// HMAC Key for FOTA chunk authentication (hex string)
// Note: Different from HMAC_PSK in credentials.h (used for data authentication)
extern const char* HMAC_FOTA_KEY;

// Key metadata
#define RSA_KEY_SIZE 2048
#define AES_KEY_SIZE 256
#define HMAC_PSK_SIZE 64

#endif // OTA_KEYS_H
