/*
 * ESP32 OTA Security Keys - Implementation
 * Auto-generated by generate_keys.py
 * 
 * ⚠️  SECURITY WARNING: These keys are embedded in firmware!
 * ⚠️  In production, use secure key storage (efuse, secure boot, etc.)
 */

#include "application/keys.h"

// RSA-2048 Public Key for signature verification
const char* SERVER_PUBLIC_KEY = 
    "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsQ8Pqe/fv8u0voGPk0/7\nZlNk7ktc6USP3RNCjnlY19HMk86dULDrXZ257oCinbtz0/TVCGVjZmJiFtubeVzW\nA5nCZKcfMeimBUXEy9Yrux9xnSSxZPYJv2UEasAq24qTr8WAAUWYyyfhqZKVX5S3\novtL0lo/936beQK+X9DNWWjy05B3JgurS3axuPTX36mclcgPyTDpgiBQ5N3uzoKl\nIZJKO0x9g33wPqnkQd6q7SJuA4nMvIoXXGcKSK+nz6GEpR7NSx5kRZqsObdvYgd4\njxMtLImB+aVPnrA58gP/YKw+HZh4o5fLDYy6e/7VtNqVPTubOEPGrr0/T0s91Bo/\niwIDAQAB\n-----END PUBLIC KEY-----\n";

// AES-256 Key for firmware decryption (32 bytes)
// MUST MATCH flask/keys/aes_firmware_key.bin: a27bb3da294244cb3e797760a00abd1fd056379d313f4122e23fa469e0e84ae6
const uint8_t AES_FIRMWARE_KEY[32] = {
    0xA2, 0x7B, 0xB3, 0xDA, 0x29, 0x42, 0x44, 0xCB, 
    0x3E, 0x79, 0x77, 0x60, 0xA0, 0x0A, 0xBD, 0x1F, 
    0xD0, 0x56, 0x37, 0x9D, 0x31, 0x3F, 0x41, 0x22, 
    0xE2, 0x3F, 0xA4, 0x69, 0xE0, 0xE8, 0x4A, 0xE6
};

// HMAC Pre-Shared Key for chunk authentication
const char* HMAC_PSK = "16ecd7da91ce8db9c0de79be4da968e98923a3bca23e2581dfa24bce23297a54";