/*
 * ESP32 OTA Security Keys - Implementation
 * Auto-generated by generate_keys.py
 * 
 * ⚠️  SECURITY WARNING: These keys are embedded in firmware!
 * ⚠️  In production, use secure key storage (efuse, secure boot, etc.)
 */

#include "application/keys.h"

// RSA-2048 Public Key for signature verification
const char* SERVER_PUBLIC_KEY = 
    "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw0gtUSm2vF/4APLWwawE\nD2S4WNU06ojURK9Zlo04iAhoqyEZ/KXYrbWALsvK/fxEpXD7LDS+2HUi6OVKvUWj\ngKbKFbpEXaLSKrSx+NtK5u2/u49H3yZozEm10Ll4SuU1o1rVMnYSzkdMqMfa1N0p\nKwqeJQTsRQ9N+Z6gpqfUi1GP8Ji1uoFtiQWOzocYS9ai8gxiaJnPG0Ye+16Odq1/\n2TW/r47Ko4aKyS1+X4wHPVFBjGKTO6TP8l5yMt6jyfDN/sDLmjDetzAr39/BOxQ9\nQjAdXHrw0iTm1S4YxQwk1UG7wQMGYTtJAo5aOAfVZQU5C1U5Ez3+PZ2ErY5SiXhF\nBwIDAQAB\n-----END PUBLIC KEY-----\n";

// AES-256 Key for firmware decryption (32 bytes)
// MUST MATCH flask/keys/aes_firmware_key.bin: bc153d62029fef37ff08b81bba91f0e62f50e9bbe5609fe5f3b36890a8c8f70c
const uint8_t AES_FIRMWARE_KEY[32] = {
    0xBC, 0x15, 0x3D, 0x62, 0x02, 0x9F, 0xEF, 0x37, 
    0xFF, 0x08, 0xB8, 0x1B, 0xBA, 0x91, 0xF0, 0xE6, 
    0x2F, 0x50, 0xE9, 0xBB, 0xE5, 0x60, 0x9F, 0xE5, 
    0xF3, 0xB3, 0x68, 0x90, 0xA8, 0xC8, 0xF7, 0x0C
};

// HMAC Pre-Shared Key for chunk authentication
const char* HMAC_PSK = "fb7956d796c2359eee9fdcf9726d728b576fce9570dac869ccd33d30a8869485";